### ISSUE TITLE
Improve categorization UX for checking validity of datasets

### ISSUE THREAD

**Issue by mukeshelastic** [elastic/logs#11]
**Summary of the problem** 
Categorization by design provides better results on unstructured machine data with repeated patterns. Additionally, a lack of sufficient training dataset can also impact the categorization results quality.  We’d like to inform users if their datasets have either of the problems and the action they need to take for getting better categorization results.  

**Ideal solution** (optional)
When user creates the job for the first time or reconfigures it to add more datasets, we’s should show a warning message at top of the results screen describing the specific datasets not being suitable for categorization either due to high cardinality or lack of sufficiently long training dataset and suggest them to filter them. Users can choose to not take an action, how ever we will show this message again when we reload the categories page again.

**Comment by katrin-freihofner** [comment]
I had a sync with @mukeshelastic yesterday. It seems like there are two cases we need to handle:

1. If the data does not provide meaningful patterns -> this means the categories are not as useful. We can only verify this when the job is running.

2. We have too little training data (there should be a way to verify this upfront). This means we can warn our users during the ML job creation (creation should still be possible). 

In both cases we need a way to show which dataset(s) are affected and which actions can be taken.

**Comment by katrin-freihofner** [comment]
## 1.  If the data does not provide meaningful patterns...

### - ...in one dataset

<img width="1442" alt="Screenshot 2020-02-20 at 11 56 48" src="https://user-images.githubusercontent.com/20965076/74927833-a8e76600-53d8-11ea-9468-9a06695b80bb.png">

### - ...in multiple datasets
<img width="1440" alt="Screenshot 2020-02-20 at 11 56 39" src="https://user-images.githubusercontent.com/20965076/74927837-abe25680-53d8-11ea-9af0-acf5739098ed.png">

## 2.  We have too little training data...

### - ...in one dataset
<img width="1443" alt="Screenshot 2020-02-20 at 11 56 55" src="https://user-images.githubusercontent.com/20965076/74927813-9e2cd100-53d8-11ea-9051-13fefee58f72.png">

#### Setup screen (during job creation)

<img width="744" alt="Screenshot 2020-02-20 at 11 55 58" src="https://user-images.githubusercontent.com/20965076/74927942-d9c79b00-53d8-11ea-916c-37052dad9d4e.png">


### - ...in multiple datasets
<img width="1443" alt="Screenshot 2020-02-20 at 11 57 03" src="https://user-images.githubusercontent.com/20965076/74927809-9a994a00-53d8-11ea-9904-73794e0286b8.png">

#### Setup screen (during job creation)

<img width="744" alt="Screenshot 2020-02-20 at 11 56 10" src="https://user-images.githubusercontent.com/20965076/74927930-d16f6000-53d8-11ea-9e14-80a43b49c7a0.png">

#### Additional indicators (alert icon) to highlight what needs to change
<img width="822" alt="Screenshot 2020-02-20 at 12 06 56" src="https://user-images.githubusercontent.com/20965076/74928301-87d34500-53d9-11ea-964e-bc47cce50a69.png">

## If both happen.
<img width="1443" alt="Screenshot 2020-02-20 at 11 57 17" src="https://user-images.githubusercontent.com/20965076/74927796-940ad280-53d8-11ea-9b73-168d73431abd.png">

## A few notes
- The warning messages on the categorization view should be removable (notice the `X`)
- The warning messages on the setup screen can't be removed
- There can be 0-2 callouts on the categorization view
- If we detect that the dataset can not be categorized in a meaningful way and the user navigates to the setup screen, we should show this also in the setup screen.

**Comment by katrin-freihofner** [comment]
A few updates according to the feedback I got from @mukeshelastic 

- The warning callout in the categories view can not be removed
- I added a link to the docs
- If there is too little training data **and** no meaningful categorization we combine these in one warning.

This is an example of how the updated version looks like (multiple datasets producing too many categories)
<img width="1381" alt="Screenshot 2020-02-21 at 12 20 43" src="https://user-images.githubusercontent.com/20965076/75030667-e31e3980-54a4-11ea-9c6c-2eb4685057f7.png">

We also talked about an easier way to access and disable/enable individual datasets. This is an example of how the setup screen could look like:
<img width="749" alt="Screenshot 2020-02-21 at 12 19 59" src="https://user-images.githubusercontent.com/20965076/75031506-b0754080-54a6-11ea-94aa-7a8eda28ea5f.png">

**Comment by katrin-freihofner** [comment]
Quick update for the setup screen. With this version we are better prepared to display a large number of datasets:

<img width="951" alt="Screenshot 2020-02-28 at 09 13 39" src="https://user-images.githubusercontent.com/20965076/75522593-a3a69e80-5a0a-11ea-8771-ce5adc8391df.png">
