### ISSUE TITLE
Anomaly detection setup

### ISSUE THREAD

**Issue by katrin-freihofner** [elastic/logs#14]
**Summary of the problem** (If there are multiple problems or use cases, prioritize them)
With the new user flow, discussed in [this issue](https://github.com/elastic/logs/issues/10), we need to rethink the whole ML job setup.

**Comment by katrin-freihofner** [comment]
WIP
![logs-anomaly-setup](https://user-images.githubusercontent.com/20965076/79733602-abd9d680-82f5-11ea-9c8e-ceb6bd8d3439.gif)

...I think this might work to combine log rate and categorization job setups.

**Comment by katrin-freihofner** [comment]
## Full workflow

![ml-setup-logs](https://user-images.githubusercontent.com/20965076/79859108-c59c1c00-83d0-11ea-8c25-630029b075db.gif)

**Comment by katrin-freihofner** [comment]
I updated the job list to use cards:
<img width="752" alt="Screenshot 2020-04-22 at 17 42 50" src="https://user-images.githubusercontent.com/20965076/80003023-b4cad380-84c0-11ea-88b5-7ab6b0bdfac7.png">

**Comment by weltenwort** [comment]
Interesting concept - I wonder how well it scales for smaller screens and larger numbers of jobs :thinking: What are the upsides of cards from a UX perspective?

**Comment by katrin-freihofner** [comment]
@weltenwort I see the cards as a purely visual enhancement compared to the list. One could argue, that it's easier to grasp which job is already set up and which one isn't...
I don't see any issue on small screens, we have only 2 jobs for now. Do you think we will be scaling the number of jobs soon to 6+?

**Comment by weltenwort** [comment]
probably not very soon. what might come sonner, though, is the combination of ml jobs with alerts. would that be integrated into the flyout too or where would those be configured?

**Comment by katrin-freihofner** [comment]
I don't see a reason to include alerts in this flyout at the moment. I would prefer to keep those separate from each other. But I'm happy to discuss this in one of our syncs.

**Comment by katrin-freihofner** [comment]
This video is showing the full setup:
![full-setup](https://user-images.githubusercontent.com/20965076/80584913-b7727f00-8a12-11ea-8f6d-b1df586fd562.gif)

I'm going to split this up into several smaller implementation issues:

1. [Moving the setup to the flyout](https://github.com/elastic/kibana/issues/64754)
2. [Showing category and log rate anomalies in the table](https://github.com/elastic/kibana/issues/64755) (dependent on https://github.com/elastic/kibana/issues/63671)
3. [Showing the list of ML jobs in the flyout](https://github.com/elastic/kibana/issues/64757)

**Comment by katrin-freihofner** [comment]
Additional info:
- For now, we are going to keep the Categories tab
- I'm going to open additional issue, handling license issues and upgrades
- There will be a bit of cleanup for the anomalies tab, but I'm still working on that
