### ISSUE TITLE
Logs alert creation 

### ISSUE THREAD

**Issue by mukeshelastic** [elastic/logs#19]
**Summary of the problem** 

As an observability user persona, I'd like to create alerts for following use cases:
1. When the count of (ECS.field = value) > static threshold within last X time unit then send a slack message that contains document.field value

Alert definition UI

> When count of <ecs.field = value> is greater than integer within last 5 minutes

2. When the count of ( message contains <text pattern>) crosses a static threshold within the last X time unit then send me a message

Alert definition UI

> When the count of ( ecs.field contains <text pattern>) is greater than an integer threshold in last five minutes

3. document message contains a specific log pattern AND/NOT other log patterns in the same document then send a message 

Alert definition UI

> When the ecs.field contains <text pattern1>, <text pattern2> AND ecs.field does not contain <text pattern 3> in last five minutes 

4. (Stretch Goal) the count of ( message contains text pattern) for each bucket  represented by a unique value in specific ecs.field, goes beyond a static threshold

Alert definition UI

> When the count of( ecs.field contains <text pattern 1>, <text pattern2>) group by ecs.field is greater than integer threshold in last five minutes 

5. (Stretch Goal) Creating alerts from anomaly explorer tabular information

**Comment by katrin-freihofner** [comment]
![Uploading logs-alerting.gif…]()

**Comment by katrin-freihofner** [comment]
The alert conditions have been changed to the following:

<img width="634" alt="a" src="https://user-images.githubusercontent.com/20965076/78360357-f7327c00-75b6-11ea-973f-607bdab6a3ef.png">

<img width="634" alt="b" src="https://user-images.githubusercontent.com/20965076/78360354-f6014f00-75b6-11ea-9367-2e318831a15c.png">

<img width="637" alt="c" src="https://user-images.githubusercontent.com/20965076/78360335-ef72d780-75b6-11ea-81d4-f9828fbe485f.png">
