### ISSUE TITLE
[Logs] charts in alert flyout

### ISSUE THREAD

**Issue by katrin-freihofner** [elastic/logs#22]
**Summary of the problem**
Similar to Metrics we'd like to show charts in the alert flyout to help our users with the alert setup. This will make it much easier to set an appropriate threshold.

This issue should investigate how this could work for logs.

**Comment by katrin-freihofner** [comment]
![Screenshot 2020-05-26 at 10 10 07](https://user-images.githubusercontent.com/20965076/82876458-1dcabe80-9f39-11ea-9eb7-94ecc7aa8131.png)

**Comment by sgrodzicki** [comment]
Have we made any progress on this lately? We have this scheduled for 7.9, but with 3 more weeks until feature freeze (July 17), we would need a design soonish. Otherwise, we have to move this to the next release. /cc @mukeshelastic

**Comment by sgrodzicki** [comment]
https://github.com/elastic/kibana/issues/69530
