### ISSUE TITLE
Data Prep UI - Log parsing for custom logs phase 1 iteration 1

### ISSUE THREAD

**Issue by mukeshelastic** [elastic/logs#25]
**Summary of the problem** (If there are multiple problems or use cases, prioritize them)
Data Prep UI is intended to simplify getting started experience of logs ingestion. The logs can be from supported integration or any custom logs.

**User stories**
In this issue, we will consider the following user journey of onboarding custom logs

1.    User wants to analyze  logs with a custom format 
2.    User visits Logs UI and sees "parse logs" button
3.    User clicks on "parse logs"
4.    User sees two options - provide log sample or point to an index/datastream
5.    For this design iteration, we will stick to log sample workflow
6.    After user pastes sample logs, we show a parsing wait screen while we compute grok pattern that represents the log sample
7.    For this iteration, we will assume only grok parsing and that all sample logs can be represented with same grok pattern
8.   Assuming the parsing is successful, we will show users, a sample log line preview at the top, grok text box that was auto-populated with grok pattern. User will see a button to apply this pattern to see the parsing results.
e.g. for a log line like this:

 `` 109.169.248.247 - - [12/Dec/2015:18:25:11 +0100] "GETTTY /administrator/ HTTP5/1.1 200 4263 Mozilla/5.0 (Windows NT 6.0; rv:34.0) Gecko/20100101 Firefox/34.0" ``

The grok pattern text box will show 

%{IP:ipaddress} .*? .*? \[%{HTTPDATE:timestamp}\] ".*? %{PATH:path} .*?/%{NUMBER:field2} %{INT:field} %{INT:field3} .*?/.*?%{NUMBER:field5} \(.*? .*? %{NUMBER:field6}; .*?:%{NUMBER:field7}\) .*?/%{INT:field4} .*?/%{NUMBER:field8}"

9. User can hand edit this pattern to change the field names, datatype within the grok pattern
10. When user clicks apply, a table is shown below with three column - field name, field data type and parsed field value e.g. for the line shown above, the table will show 

`` field name``        ``data type``       ``field value``
``Client-IP``            ``ipaddress``       ``109.169.248.247``
``timestamp``        ``HTTPDATE``      ``[12/Dec/2015:18:25:11 +0100] ``

9. User can change the field name and data type in grok parser text box and hit apply and the table will reflect the user changes

10. If the datatype is not supported then an error message is shown below the text box. 

11. The datatype is a dropdown with values for different supported datatypes within elasticsearch.

12. On this screen, at the bottom, user sees button named 'view logs' 

13. Clicking on view logs, should ingest logs in elastic and show logs in logs UI with appropriate fields shown.

**Comment by tbragin** [comment]
Related design ticket for "Log onboarding for supported logs" 
#25": https://github.com/elastic/logs/issues/24

**Comment by katrin-freihofner** [comment]
First[ prototype](https://www.figma.com/proto/ZaU57BT6YdOmwQ84Mbwl0H/Data-prep-UI?node-id=20%3A86&viewport=-7049%2C129%2C1&scaling=min-zoom) showing a possible user flow. This is a very early prototype and only shows a small part of custom logs parsing.

**Comment by katrin-freihofner** [comment]
I have been working on a [new iteration of the prototype](https://www.figma.com/proto/ZaU57BT6YdOmwQ84Mbwl0H/Data-prep-UI?node-id=350%3A335&viewport=-116%2C-104%2C0.25&scaling=min-zoom). The new view (instead of the flyout) has the following benefits:
- clearer flow (step-by-step and progress indicator)
- more focused (no background things going on). Users won't need the information that is going on in the background.
- more space for exploring log lines
