### ISSUE TITLE
Log categories

### ISSUE THREAD

**Issue by katrin-freihofner** [elastic/logs#3]
**Summary of the problem** (If there are multiple problems or use cases, prioritize them)
As a user I want to investigate 
- logs per category
- ~~rare log messages~~(we are going to focus on categories for now)

**Filter/Search option**
Search for free text
Filter timestamp and dataset

## Next steps
**Prep**
- [x] analyze available example data in kibana dashboard
- [ ] get use cases and requirements docu

**Design**
- [ ] ~~create a basic user flow diagram~~(exploratory use case, therefore this is not needed)
- [x] create wireframes (low-fi) for each of the main usecases
- [x] think about licensing 
- [x] think about the experience for new users
- [x] grok patterns vs. more specific log lines -> will be covered in latest mockups (comment from 11-11-2019)
- [x] do we need to show example logs? Where and how? -> The first version of this feature will be without any examples.
- [x] how could we show a trend?

**Implementation**
https://github.com/elastic/kibana/issues/42776

**Comment by katrin-freihofner** [comment]
**WIP**

Layout
![layout](https://user-images.githubusercontent.com/20965076/67089130-373ba900-f1a7-11e9-8215-f3a6bff720f8.png)

Categories

a)
![cat-1](https://user-images.githubusercontent.com/20965076/67089195-5f2b0c80-f1a7-11e9-8e87-cc93bdd25814.png)
b)
![cat](https://user-images.githubusercontent.com/20965076/67089198-5f2b0c80-f1a7-11e9-92a8-9eb88d256e87.png)


Rare logs

![rare-logs](https://user-images.githubusercontent.com/20965076/67089088-17a48080-f1a7-11e9-8426-9337a00fcf4b.gif)

![init](https://user-images.githubusercontent.com/20965076/67089154-4884b580-f1a7-11e9-9684-7476138c8a3c.png)

![rare msgs](https://user-images.githubusercontent.com/20965076/67089145-40c51100-f1a7-11e9-982c-8f44e999d129.png)

**Comment by weltenwort** [comment]
This is a great start, thank you.

Looking at the mock-ups lots of questions come to mind about the semantics of the chart, the column headers, the search bar and a few more. There's a lot of room for interpretation, so I feel I should wait until you're ready to give a walk-through and give a few details on those aspects.

**Comment by katrin-freihofner** [comment]
Notes from yesterdays zoom meeting:

- We will focus on categories for now (in both, design and development)
- We will show a table/list of top categories (top 25) by message count
- Additionally, we are going to show the max anomaly score or the no. of (severe) anomalies in the table
- the table can be sorted (+pagination)
- indicate dataset (it's rare, but one cat. could have multiple datasets)
- We are going to work on a visualization of the grok pattern/regex that is easy to grasp (messages can be very long)
- Categories will have context actions
- show sparklines/trends of categories


Next
- Show examples for categories
- Examples can have context actions

**Comment by katrin-freihofner** [comment]
A quick sketch of how the things we agreed on (see comment above) could look like

![IMG_20191028_120020_2](https://user-images.githubusercontent.com/20965076/67673569-a91bab80-f97a-11e9-847b-4d401c46f44a.jpg)

**Comment by weltenwort** [comment]
That looks great. What does the "+201" besides the sparkline mean?

**Comment by katrin-freihofner** [comment]
"+ 201 messages compared to the previous timeframe"

I think a number added to the sparkline could make sense, especially to indicate tiny changes? What is your opinion on that?

**Comment by weltenwort** [comment]
So you mean it's the difference between the displayed count (calculated by summing over the values in `(startTime, startTime + timeframeDuration)`) and the sum over the values within `(startTime - timeframeDuration, startTime)`?

**Comment by katrin-freihofner** [comment]
I'm thinking about adding a visual indicator for the dataset. 

![cat](https://user-images.githubusercontent.com/20965076/67692582-a5028480-f9a0-11e9-8e09-41af9d4c5aa1.png)

**Comment by jasonrhodes** [comment]
I like where this is headed -- have we considered using the non regex version of the pattern? I think they are both pretty similar in information but losing all of the `.+?` characters would make it much easier to parse at a glance, I think...

**Comment by katrin-freihofner** [comment]
> I like where this is headed -- have we considered using the non regex version of the pattern? I think they are both pretty similar in information but losing all of the `.+?` characters would make it much easier to parse at a glance, I think...

Yes, this is still an open point (see checkboxes in the issue description)

**Comment by tbragin** [comment]
@katrin-freihofner Thank you for capturing the notes (sorry I didn't get to it quickly enough). I like this direction as well!

**Comment by katrin-freihofner** [comment]
In yesterdays meeting we review the mockup above and will continue as follows:

- The dataset should get it's own column
- The ML setup for categories could be separate from log rate (at least for now). We will use the simplest setup possible which will look quite the same as for the log rate tab. 
- We want to try to color code the ML score
- Try to use our ned EUI datagrid
- The number (+20%) indicating trend not obvious how to interpret? Could be explained via a tooltip.
- We could skip the search for the first iteration

Context actions
- Analyze in ML
- Expand examples

Rare messages will be handled in a follow up issue.

**Comment by katrin-freihofner** [comment]
Preview ;)
<img width="1441" alt="Screenshot 2019-10-30 at 11 20 55" src="https://user-images.githubusercontent.com/20965076/67849801-7521c100-fb07-11e9-9bb4-099e19ba6afb.png">
<img width="1441" alt="Screenshot 2019-10-30 at 11 21 21" src="https://user-images.githubusercontent.com/20965076/67849803-77841b00-fb07-11e9-9b1e-bd0a7e5e91af.png">


Missing:
- the pattern visualization
- any context actions (Examples...)
- Setup

...if the setup is the same as in Log rate, I'm wondering if we need any mockups. 🤔

**Comment by weltenwort** [comment]
That looks awesome IMHO :heart: I think the colored datasets in the table are useful to pattern-match visually.

Should the dataset badges in the filter area have visible/hidden icons?

![grafik](https://user-images.githubusercontent.com/973741/67854151-1c0a5b00-fb10-11e9-9f8b-3d5bbdee965a.png)
![grafik](https://user-images.githubusercontent.com/973741/67854167-23c9ff80-fb10-11e9-867e-f11318af24fa.png)

We talked about a "Analyse in ML" button on the panel header akin to the log rate page. Just mentioning so we don't forget :wink:

> The number (+20%) indicating trend not obvious how to interpret? Could be explained via a tooltip.

The tooltip could show the actual values, e.g.

```
previous ~1h: 123
current ~1h: 321
```

> if the setup is the same as in Log rate, I'm wondering if we need any mockups

I think we don't need them in this case. Where do we want to put the warning callouts on the page? Beneath the panel header?

**Comment by sophiec20** [comment]
Looks good.

Do we have an idea of typical length of category (even against our current example data)? I wonder if we may need to wrap the category rather than truncate.

I'm not sure I see that value in the (+20%) number. There could be drops and peaks in the count which gives a net zero change. Picking 1h may not be optimal for showing an issue. I think that the spark line indicates trend better. This ties in with below..

Regarding the spark line, if the time picker is selected for "last 15m" then the spark line ideally extends back further in time. What are the thoughts here? We would only have one data point to plot if set to last 15m. Perhaps we could go back last 10 buckets if range of time picker is small?

**Comment by weltenwort** [comment]
> We would only have one data point to plot if set to last 15m. Perhaps we could go back last 10 buckets if range of time picker is small?

Good point. I wonder how we can include more data, though, without adding an x-axis and still being intuitive.

**Comment by katrin-freihofner** [comment]
@weltenwort 
> I think we don't need them in this case. Where do we want to put the warning callouts on the page? Beneath the panel header?

Yes, exactly

> We talked about a "Analyse in ML" button on the panel header akin to the log rate page. Just mentioning so we don't forget

Good point, thank you!


@sophiec20 


> I'm not sure I see that value in the (+20%) number. There could be drops and peaks in the count which gives a net zero change. Picking 1h may not be optimal for showing an issue. I think that the spark line indicates trend better. This ties in with below..

I think it has it's value. First of all, it helps us accessibility-wise. Additionally, minor changes and also extreme changes will be much easier to spot.

**Comment by katrin-freihofner** [comment]
Latest update
<img width="1443" alt="Screenshot 2019-10-30 at 16 48 23" src="https://user-images.githubusercontent.com/20965076/67874379-225efe00-fb35-11e9-8d87-b5d838d479a8.png">

Felix currently helps me figuring out what's the best way to include context actions to the data grid. 

https://www.figma.com/file/T08kdh6YQcVCx1tzljqNHF/Logs-ML-Integration?node-id=0%3A1

**Comment by katrin-freihofner** [comment]
After our discussion in yesterday's design weekly, we are back to the table. The main reason is that data grid currently only allows columns with equal width and we definitely want to have more space for the log message/category.

![categories](https://user-images.githubusercontent.com/20965076/67939088-1cb6f600-fbd1-11e9-9508-356e0fc5bbfe.gif)

**Comment by katrin-freihofner** [comment]
Following our discussions at EAH I updated the following:
- pattern visualization (single *)
- Placement of actions button
- adding dataset column


Which leads us to (without examples)
![logs-cat](https://user-images.githubusercontent.com/20965076/68582673-9b3a5000-047b-11ea-8fdb-489290841ec2.gif)


...and (with examples)
![logs-examples](https://user-images.githubusercontent.com/20965076/68582680-9fff0400-047b-11ea-9537-79d6bfcf42df.gif)

**Comment by roncohen** [comment]
@katrin-freihofner I see the little blue thing moved to the right and is now overlayed on the message field :)
Is that also the direction we're going on the "Stream" page? we should make sure it's consistent

**Comment by katrin-freihofner** [comment]
> @katrin-freihofner I see the little blue thing moved to the right and is now overlayed on the message field :)
> Is that also the direction we're going on the "Stream" page? we should make sure it's consistent

@roncohen sure, it needs to be consistent with the stream view. To be honest, I'm not sure if we should move it to the right, or keep it left. Also, as it really stands out, therefore I think it's fine either way.

**Comment by mark54g** [comment]
Quick question on the filter section of the UI.

Will this update make the behavior similar to discover with the + and - ?

**Comment by weltenwort** [comment]
@mark54g what behavior in discover are you referring to? This is about showing the top N message patterns derived from the log messages via the ml categorization feature.

**Comment by mark54g** [comment]
@weltenwort -
In discover, you can take messages and add fields to do positive/negative filtering
It would be good to have similar functionality in the logs UI

**Comment by tbragin** [comment]
@mark54g We have this functionality in the Logs >> Stream app. 

Finding it is a bit of a different story, you have to mouse over an entry and you'll see a little blue indicator on the right, which brings out a fly out. We are trying to improve that experience

<img width="1270" alt="Screen Shot 2019-11-11 at 6 36 20 AM" src="https://user-images.githubusercontent.com/933397/68595083-aaa2a480-044d-11ea-95f3-a20e1a8df52b.png">

<img width="1271" alt="Screen Shot 2019-11-11 at 6 36 30 AM" src="https://user-images.githubusercontent.com/933397/68595085-aaa2a480-044d-11ea-94db-01b1459baa02.png">

**Comment by mark54g** [comment]
Thanks @tbragin 
I just recall someone mentioning having that consistency would be wonderful (keeping it similar to Discover)

**Comment by tbragin** [comment]
@mark54g Ok. Happy to discuss, but let's take it to a separate issue, since it's unrelated to log categories feature we're discussing here. Btw, Discover UX is going to change to be based on the EUI datagrid ([link](https://elastic.github.io/eui/#/tabular-content/data-grid)), so the plus / minus controls are not going to be there after that overhaul.

**Comment by mark54g** [comment]
Sorry. Will do
