### ISSUE TITLE
[Log rate UI] colors for annotations indicating anomalies

### ISSUE THREAD

**Issue by katrin-freihofner** [elastic/logs#4]
I'd like to improve on the color-scheme used for showing anomalies in the bar charts:

<img width="971" alt="Screenshot 2019-10-25 at 10 30 18" src="https://user-images.githubusercontent.com/20965076/67557851-272b4880-f716-11e9-944f-33c4bbe69212.png">

**Comment by katrin-freihofner** [comment]
As discussed in todays design meeting:
<img width="1014" alt="Screenshot 2020-01-23 at 15 56 23" src="https://user-images.githubusercontent.com/20965076/72995278-ecaa7800-3df8-11ea-93ee-1527ff1340ed.png">

Depending on: https://github.com/elastic/elastic-charts/issues/522

**Comment by katrin-freihofner** [comment]
We will use the same colors as Machine learning to make it as easy as possible for users.

**Comment by formgeist** [comment]
The Elastic Charts team has provided us with an example use of the existing charts library that enables us to show annotations as described above. They have opened a few enhancements for the legend and the marker widths to be dynamic. Please see their example described here https://github.com/elastic/elastic-charts/issues/522#issuecomment-587520485
