### ISSUE TITLE
Actions/Integrations menu: update look & feel

### ISSUE THREAD

**Issue by katrin-freihofner** [elastic/logs#5]
**Summary of the problem** (If there are multiple problems or use cases, prioritize them)
The current actions menu (holding links to other solutions) is overwhelming and hard to grasp/read. Furthermore, we have this kind of menu all over observability - but not consistent.

**Ideal solution** (optional)
One unified menu, with consistent icons and labels. Additionally, we can experiment with separating primary and secondary actions or actions within the same app vs. linking to other apps

I think this could be shared across observability.

Figma file: https://www.figma.com/file/0XC8Ie13YsP9Q3ZuGimLSw/context-menu

**Comment by alvarolobato** [comment]
Agreed to make this a quick fix, something simple that can be implemented for this iteration.

**Comment by katrin-freihofner** [comment]
1) I suggest to add a description and work on the wording of the existing links. 
<img width="405" alt="Screenshot 2019-12-09 at 15 16 10" src="https://user-images.githubusercontent.com/20965076/70442552-dfc70480-1a96-11ea-8892-a7db998284f7.png">


2) I'd like to introduce some kind of separator to distinguish between different kinds of actions.
<img width="601" alt="Screenshot 2019-12-09 at 13 22 24" src="https://user-images.githubusercontent.com/20965076/70442578-eb1a3000-1a96-11ea-8caf-68e806350ff7.png">


3) We could group links of the same app. Could look like:
a) show all links immidiatly
<img width="677" alt="Screenshot 2019-12-09 at 13 22 11" src="https://user-images.githubusercontent.com/20965076/70442593-f1101100-1a96-11ea-9cf0-9ba2ffa0034b.png">


b) use a two step interaction, where first the solution is selected and then the entity (for example: host, pod, container)
<img width="927" alt="Screenshot 2019-12-09 at 15 24 49" src="https://user-images.githubusercontent.com/20965076/70443245-194c3f80-1a98-11ea-8077-99bc007eed8a.png">

(Visit EUI to see this in action: https://elastic.github.io/eui/#/navigation/context-menu)

**Comment by sgrodzicki** [comment]
As for

> We could group links of the same app

I'm a bit worried this would lead to promoting the individual app approach (which is technically correct) instead of a unified observability approach (which we try to highlight)

**Comment by katrin-freihofner** [comment]
In yesterday's design weekly sync we discussed to try out this version - where the links are grouped by pod, container, host. The menu on the left is a screenshot of the current state, the one on the right, the new version.

<img width="757" alt="Screenshot 2019-12-12 at 07 48 50" src="https://user-images.githubusercontent.com/20965076/70689232-f5654580-1cb3-11ea-9e92-d0aeb424692c.png">

<img width="768" alt="Screenshot 2019-12-12 at 07 48 32" src="https://user-images.githubusercontent.com/20965076/70689238-fac29000-1cb3-11ea-87a6-f16adca8fdde.png">

**Comment by formgeist** [comment]
@katrin-freihofner I really like the new organization of the options. Not sure if this was mentioned in the feedback in yesterday's review, but I think the "Check domain" and "Trace details" headings don't display themselves as links. Wondering if we need to keep them as headings and add a proper text link, unless you're thinking about some styling updates to the headings when they don't have multiple links?

**Comment by katrin-freihofner** [comment]
Yes @formgeist I agree, I would like to spend some time working on the text styles.

**Comment by katrin-freihofner** [comment]
This would leed us to:

<img width="777" alt="Screenshot 2019-12-16 at 14 13 31" src="https://user-images.githubusercontent.com/20965076/70909677-43f54580-200e-11ea-8e8b-8c72f027c9c7.png">

...the left one is the current version, the one on the right the update.

**Comment by katrin-freihofner** [comment]
An example from uptime with disabled links:
<img width="820" alt="Screenshot 2019-12-16 at 14 41 57" src="https://user-images.githubusercontent.com/20965076/70911451-3b067300-2012-11ea-9dd9-517537544a09.png">

**Comment by formgeist** [comment]
@katrin-freihofner Nit-picking here, but wouldn't we have "Domain details" as the section header and "Check domain" as the link the Uptime example?

In general, I really like the new format, it's much more organized and less busy visually which helps in getting to the right option faster. There are some implementation details around the links themselves, I've mentioned using the https://elastic.github.io/eui/#/display/list-group component so the links get a larger click area, and the items in the list have some more space. I would also like to have our tech writer look at the copy and see how they might improve those headings and descriptions. Right now they all feel very repetitive, which might give the impression to the user that they're somewhat redundant.

I dig where this is going, great job leading this effort 👍

**Comment by katrin-freihofner** [comment]
@formgeist I 100% agree - the current copy is more a placeholder, I was hoping someone could help me with that.
Thank you for your feedback and help - especially using the list group was a great idea!
