### ISSUE TITLE
Exploring UX for showing premium tier features to basic/free tier users

### ISSUE THREAD

**Issue by mukeshelastic** [elastic/logs#9]
**Summary of the problem** 
Today basic licensed user do not see premium features which may be of interest to them but they are just not aware of it. This is  discoverability problem that prevents users with restricted license realize the full feature set in logs UI. 

**Ideal solution** (optional)
When user with basic/restricted license logs in and visits logs UI, she sees both categories, and logs rate tabs. If she clicks on either, she is shown a pop-up message that tells her a little bit about this feature and a link to learn more. The message has two calls to action (CTA) - (from Left)  1. Upgrade to Premium (highlighted in blue background)and second Link to learn about subscription plans. If they click outside of pop up message indicating they'd not like to take any action, the pop up disappears. if they click on Upgrade to Premium, then we will automatically upgrade their license to premium (check if this is possible for all restricted tiers) If it is not possible to upgrade their tiers to premium then we will open managing licenses page in another tab. If the click on the other CTA - link to learn about subscription, then we will take them to the related page. 

**List known (technical) restrictions and requirements**

**Are there any pages or actions that relate to this feature?**

**Comment by mukeshelastic** [comment]
Hi @katrin-freihofner - Sebastian, Jason and I were chatting about 7.7 roadmap items yesterday and I mentioned this issue as a low cost, low hanging fruit that we could deliver in 7.7. They shared few pieces of feedback. 

- Ideally it will be nice to bring similar experience across all observability solutions. So if you agree, we may need to co-ordinate with other obs teams 
- We should think about the UX for open source (e.g self managed, AWS ES)users 
-  We should also think through if we want to show any teaser preview of this feature in addition to just show the subscriptions message.

**Comment by katrin-freihofner** [comment]
I'd like to propose to have the ML tabs available all the time (not only for platinum users) and promote/describe the features there.

This could look like this:
<img width="1441" alt="Screenshot 2020-01-28 at 13 50 27" src="https://user-images.githubusercontent.com/20965076/73265513-636abb00-41d5-11ea-8c0d-1e95d59526bf.png">

To make this happen we would need:
### Illustration
If we decide we want to have this in other places too, we could ask for the appropriate illustration.

### Wording
Besides a good description of what to expect and which benefits these features have we should add links to information about the subscription and its costs.

**Comment by skearns64** [comment]
cc @grabowskit @VijayDoshi @snide - I'm a big +1 to thinking through the UX around how to tastefully show paid features to free/basic users. I don't think we need to hold back progress on this specific issue, but would love to start the thinking at the Stack level and migrate to a single or small number of different experiences according to the scenario and needs

Also worth noting that we should be sure to handle the various cases, like: 1) have not yet started trial, so they can just self-generate. 2) basic license, but already used their trial for this major version. 3) currently expired trial license. 4) User doesn't have access to start a trial, etc.

**Comment by snide** [comment]
I like @katrin-freihofner's design and agree we should do more up-selling. I'd prefer a video that can really show off the feature, but an illustration is low effort and can help.

**Comment by mukeshelastic** [comment]
> Also worth noting that we should be sure to handle the various cases, like: 1) have not yet started trial, so they can just self-generate. 2) basic license, but already used their trial for this major version. 3) currently expired trial license. 4) User doesn't have access to start a trial, etc.

Thanks for the feedback @skearns64. We will account for these cases as we iterate on UX. 

>  I'd prefer a video that can really show off the feature, but an illustration is low effort and can help.

Video will be a much better experience. Effort for making the video isn't much but I am unclear on the cost of logistics of hosting, embedding on the page. If we have a precedent on how to do that in other solutions, then a showing a video will be worth it.

**Comment by katrin-freihofner** [comment]
I discussed this issue with @mukeshelastic in our sync yesterday. We will start with the same approach as APM: 

![log-rate-ml](https://user-images.githubusercontent.com/20965076/74424729-c9e90d80-4e52-11ea-8fd4-7af7807e4665.gif)

Depending on the license there are several options for this dropdown.

1. No platinum license and has not used the free trial yet
![start trial](https://user-images.githubusercontent.com/20965076/74424799-e84f0900-4e52-11ea-9ad9-03d26a0cc259.png)

2. Free trial or platinum license but no ML jobs yet enabled
The `Create...job` buttons link to the corresponding tab with the setup screen.
![Trial or Premium no ML enabled](https://user-images.githubusercontent.com/20965076/74424812-f00ead80-4e52-11ea-9c59-6c5cc3419555.png)

3. Free trial or platinum license and ML jobs enabled
The `View...in Machine learning` buttons link to these ML jobs in the ML app.
![Trial or Premium all ML jobs enabled](https://user-images.githubusercontent.com/20965076/74424825-f3a23480-4e52-11ea-9d9b-eab5467187de.png)

4. Free trial or platinum license and single ML job enabled
The `Create...job` button links to the corresponding tab with the setup screen.
The `View...in Machine learning` button links to this ML job in the ML app.
![Trial or Premium single ML job enabled](https://user-images.githubusercontent.com/20965076/74424828-f6048e80-4e52-11ea-9eb8-1d9c9e709a66.png)

5. Trial over
![no premium](https://user-images.githubusercontent.com/20965076/74424920-1c2a2e80-4e53-11ea-99bf-98906de157b8.png)

**Comment by weltenwort** [comment]
What happens to the existing jobs and data when the trial expires? Will we implement some sort of cleanup routine? How do we communicate that to the user?

**Comment by katrin-freihofner** [comment]
> What happens to the existing jobs and data when the trial expires? Will we implement some sort of cleanup routine? How do we communicate that to the user?

Good question - will the data still be accessible?

**Comment by alvarolobato** [comment]
Do we know what happens currently? AFAIK the users can already start a trial, we are just not showing it in this UI, right?

**Comment by katrin-freihofner** [comment]
> Do we know what happens currently? AFAIK the users can already start a trial, we are just not showing it in this UI, right?
Yes, that's true as far as I know.

I'm not sure about what happens to my collected ML data when the trial is over.

**Comment by weltenwort** [comment]
According to the ML docs the datafeeds are stopped and jobs closed, but the previously collected results remain available.

**Comment by katrin-freihofner** [comment]
Ok, this means we have another option, where the trial is expired but there are already ML jobs in place. This would also mean, that the `Log rate` and `Categories` tabs stay. And the popover could look like this:
  
![no premium trial expired](https://user-images.githubusercontent.com/20965076/74518656-822aba80-4f14-11ea-8515-4055b6bbea0e.png)
